version: '3.7'

networks:
  takecontrol-dev:
    driver: bridge

services:
  takecontrol-app-dev:
    build: ./docker.Dev/
    ports:
      - "5167:5167"
    depends_on:
     - "postgres"
    volumes:
      - ./:/app
    environment:
      DB_CONNECTION_STRING: "host=postgres;port=5432;database=${DATABASE_NAME};username=${PG_USERNAME};password=${PG_PASSWORD}"
    networks:
     - takecontrol-dev
  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
     - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: "${DATABASE_NAME}"
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - takecontrol-dev
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - takecontrol-dev
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports: 
        - 27017:27017
volumes:
 db-data:
 pgadmin-data:

